// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urjcjboxtesntibsvgvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyamNqYm94dGVzbnRpYnN2Z3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODM4OTcsImV4cCI6MjA2NjM1OTg5N30.CIrRuGU2ruEdgddTxF8BUMTi2MRv2VmkGM55QANhacQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);